name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read VERSION file
        id: version
        run: echo "VERSION=$(head -n1 VERSION)" >> $GITHUB_OUTPUT

      - name: Build and publish image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        run: |
          chmod +x ./build.sh
          ./build.sh "$IMAGE_NAME" "$IMAGE_TAG"
          docker push "$IMAGE_NAME:$IMAGE_TAG"
